services:
  postgres:
    container_name: postgreSQL
    build:
      context: postgreSQL/.
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - Transcendence

    django:
      