services:
  # postgres:
  #   container_name: postgreSQL
  #   build:
  #     context: backend/postgreSQL/.
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   expose:
  #     - "5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - Transcendence

  postgres:
    image: postgres
    restart: always
    volumes:
    - postgres:/var/lib/postgresql/_data
    networks:
    - Transcendence
    expose:
    - "5432"
    environment:
      POSTGRES_PASSWORD: 29KezYvQmJ4wygF
      POSTGRES_USER: chief
      POSTGRES_DB: Transcendence

  django:
    container_name: django
    build:
      context: backend/django/.
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - django:/transcendence
    networks:
      - Transcendence
    depends_on:
      - postgres
    
  nginx:
    container_name: nginx
    build:
      context: front
      dockerfile: docker/nginx/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - Transcendence
    
  
volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/postgres
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/django

networks:
  Transcendence:
    driver: bridge