services:
  postgres:
    container_name: postgreSQL
    build:
      context: postgreSQL/.
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - Transcendence

  django:
    container_name: django
    build:
      context: django/.
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - django:/transcendence
    networks:
      - Transcendence
    depends_on:
      - postgres
  
volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/postgres
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/django

networks:
  Transcendence:
    driver: bridge